### PR TITLE
auto update plugin manifest in index repo on tagged releases

### PR DESCRIPTION
**Pull request by rajatjindal**

### CODE REVIEW

**Review by vdice — COMMENTED** [review]
I see this action also runs for pushes to branches matching `"v[0-9]+.[0-9]+"` -- just double-checking that the 'Release Plugin' step should run in these cases as well.

**Comment by rajatjindal** [comment]
> I see this action also runs for pushes to branches matching `"v[0-9]+.[0-9]+"` -- just double-checking that the 'Release Plugin' step should run in these cases as well.

that is a good point. I don't think we need to run this action for "v[0-9]+.[0-9]+"` unless there is a specific requirement. do you see any issue if we just remove that part from the trigger config?

**Comment by vdice** [comment]
> do you see any issue if we just remove that part from the trigger config?

No, althought I haven't really been tuned in to this repo and its CI needs.  But if we we don't need that trigger for this workflow, sounds good, we should remove.

**Comment by bacongobbler** [comment]
> I don't think we need to run this action for "v[0-9]+.[0-9]+"` unless there is a specific requirement.

I'm confused. I thought that was the whole point of this PR. If we tag `v0.1.0`, this change add v0.1.0 to the index.

Can you please help catch me up on the context behind this change?

**Comment by bacongobbler** [comment]
Oh wait you're talking about BRANCHES, not tags. Sounds good to me!

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
